---
kind: pipeline
type: docker
name: bookhunter

steps:

    - name: build
      image: golang
      volumes:
          - name: config
            path: /app/config
          - name: data
            path: /data/book
      environment:
          BASE_DIR: /data/book/calibre/down-book
          BOOKHUNTER_BIN: /data/book/bookhunter
      commands:
          - $BOOKHUNTER_BIN --config /app/config tianlang -e -f epub -f zip -r --source lanzou -t 4 -d $BASE_DIR/tianlang -t 2 --ratelimit 120
volumes:
    - name: config
      host:
          path: /root/.config/bookhunter
    - name: data
      host:
          path: /data/book

