---
kind: pipeline
name: bookhunter

steps:

    - name: build
      image: debian
      volumes:
          - name: config
            path: /app/config
          - name: data
            path: /data/book
      environment:
          BASE_DIR: /data/book/calibre/down-book
          BOOKHUNTER_BIN: /data/book/bookhunter
          CALIBRE_LIBRARY:
              from_secret: calibre_library
      commands:
          - apt update & apt install rename
          - mkdir books
          - $BOOKHUNTER_BIN --config /app/config tianlang -e -f epub -f zip -r --source lanzou -t 4 -d ./books -t 2 --ratelimit 120
          - rename  's/.*\.epub$/ebook-$N.epub/' ./books/*.epub
          - /data/book/booktool-linux-x64 rename -j -p ./books
          - calibredb --with-library="$CALIBRE_LIBRARY" add -r --add=epub --automerge=ignore ./books
          - rm -rf ./books
volumes:
    - name: config
      host:
          path: /data/vdb1/docker/config/bookhunter
    - name: data
      host:
          path: /data/book

