FROM debian:buster-slim AS fake-hwaddr


RUN apt-get update && \
    apt-get install -y --no-install-recommends --no-install-suggests gcc libc6-dev make

COPY fake-hwaddr ./fake-hwaddr/

RUN cd fake-hwaddr && make
