name: Build Book-Helper Images
on: workflow_dispatch
env:
  IMAGE_NAME: book-helper
  VERSION: 0.0.1
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Set Environment Variable
        run: | 
          bookhunter_version=$(curl -s "https://api.github.com/repos/bookstairs/bookhunter/releases/latest" | jq '.tag_name' -r | sed 's/v//g')
          bookimporter_version=$(curl -s "https://api.github.com/repos/jianyun8023/bookimporter/releases/latest" | jq '.tag_name' -r | sed 's/v//g')
          
          echo "bookhunter_version=$bookhunter_version" >> $GITHUB_ENV
          echo "bookimporter_version=$bookimporter_version" >> $GITHUB_ENV
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          echo "IMAGE_ID=$IMAGE_ID" >> $GITHUB_ENV
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: docker/book-helper
          platforms: linux/amd64,linux/arm64
          labels: runnumber=${GITHUB_RUN_ID}
          build-args: |
            bookhunter_version=${{ env.bookhunter_version }}
            bookimporter_version=${{ env.bookimporter_version }}
          push: true
          tags: |
            ${{ env.IMAGE_ID }}:${{ env.VERSION }}
            ${{ env.IMAGE_ID }}:latest
