name: Build Book-Helper Images
on: workflow_dispatch
env:
  IMAGE_NAME: book-helper
  VERSION: 0.0.1
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build image
        working-directory: "book-helper"
        run:  |
          bookhunter_version=$(curl -s "https://api.github.com/repos/bookstairs/bookhunter/releases/latest" | jq '.tag_name' -r | sed 's/v//g')
          bookimporter_version=$(curl -s "https://api.github.com/repos/jianyun8023/bookimporter/releases/latest" | jq '.tag_name' -r | sed 's/v//g')
          docker build -t $IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}" --build-arg bookhunter_version=${bookhunter_version} --build-arg bookimporter_version=${bookimporter_version} .

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker tag $IMAGE_NAME $IMAGE_ID:latest
          docker push $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:latest