name: Build EasyConnect Docker Images

on: workflow_dispatch

env:
  IMAGE_NAME: docker-easyconnect
  EC_URL: "http://download.sangfor.com.cn/download/product/sslvpn/pkg/linux_767/EasyConnect_x64_7_6_7_3.deb"
  VERSION: "7.6.7"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build image
        working-directory: "easy-connect"
        run:  |
          docker build -f Dockerfile.fake-hwaddr -t fake-hwaddr  --label "runnumber=${GITHUB_RUN_ID}" .
          docker build --build-arg EC_URL=$EC_URL -f Dockerfile -t $IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}"  .

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
         
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker tag $IMAGE_NAME $IMAGE_ID:latest
          docker push $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:latest