#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2019 P3TERX <https://p3terx.com>
# Copyright (C) 2019 KFERMercer <KFER.Mercer@gmail.com>
# 
# <https://github.com/KFERMercer/OpenWrt-CI>
#

name: OpenWrt-CI

on:
  push:
    branches:
      - master
  # schedule:
  #   - cron: 0 20 * * *
  # release:
  #   types: [published]
env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  CONFIG_FILE: .config
  SSH_ACTIONS: true
  TZ: Asia/Shanghai
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master
      - name: Space cleanup
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
          chmod +x ./tool.sh
          ./tool.sh install_dep
          df -h

      - name: clone lede
        run: ./tool.sh clone
      - name: Update feeds
        run: ./tool.sh update_feeds
      - name: Generate configuration file
        run: ./tool.sh build_config
      - name: SSH connection to Actions
        uses: P3TERX/debugger-action@master
        if: env.SSH_ACTIONS == 'true'
      - name: Make download
        run: ./tool.sh make_download
      - name: Compile firmware
        run: ./tool.sh compile_firmware
      - name: Upload OpenWrt Packages
        uses: actions/upload-artifact@master
        with:
          name: OpenWrt Packages
          path: ./lede/bin/packages/
      - name: Clean Packages
        run: rm -rf ./lede/bin/targets/x86/64/packages
      - name: Upload OpenWrt firmware
        uses: actions/upload-artifact@master
        with:
          name: OpenWrt firmware
          path: ./lede/bin/targets/x86/64
      - name: WeChat notification
        run: curl https://sc.ftqq.com/${{ secrets.SCKEY }}.send?text=OpenWrt_X64编译完成