name: OpenWrt-CI

on: workflow_dispatch
env:
  REPO_URL: https://github.com/openwrt/openwrt
  REPO_BRANCH: v24.10.0-rc7
  SOURCE_PATH: './openwrt-source'
  CONFIG_FILE: .config
  SSH_ACTIONS: false
  TZ: Asia/Shanghai
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master
      - name: Space cleanup
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
          chmod +x ./openwrt/tool.sh
          ./openwrt/tool.sh install_dep
          df -h
      - name: Build System Setup
        uses: sbwml/actions@openwrt-build-setup
      - name: Install LLVM
        uses: sbwml/actions@install-llvm
      - name: clone OpenWrt
        run: ./openwrt/tool.sh clone
      - name: Update feeds
        run: ./openwrt/tool.sh update_feeds
      - name: Generate configuration file
        run: ./openwrt/tool.sh build_config
      - name: Make download
        run: ./openwrt/tool.sh make_download
      - name: Compile firmware
        run: ./openwrt/tool.sh compile_firmware
      - name: Upload OpenWrt Packages
        uses: actions/upload-artifact@master
        with:
          name: OpenWrt Packages
          path: ${{env.SOURCE_PATH}}/bin/packages/
      - name: Clean Packages
        run: rm -rf ${{env.SOURCE_PATH}}/bin/targets/x86/64/packages
      - name: Upload OpenWrt firmware
        uses: actions/upload-artifact@master
        with:
          name: OpenWrt firmware
          path: |
            ${{env.SOURCE_PATH}}/bin/targets/
      - name: WeChat notification
        run: curl https://sctapi.ftqq.com/${{ secrets.SCKEY }}.send?text=OpenWrt_X64编译完成
