# This is a basic workflow to help you get started with Actions

name: Convert sub

on: workflow_dispatch
env:
#  REPO_URL: tossp/redpill-tool-chain
#  REPO_BRANCH: master
#  WORK_DIR: redpill-tool-chain
  TZ: Asia/Shanghai

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Download subconverter
        uses: Legion2/download-release-action@v2.1.0
        with:
          repository: tindy2013/subconverter
          tag: 'v0.7.1'
          path: ./
          file: subconverter_linux64.tar.gz
      - name: subconverter
        run: |
          tar -zxvf subconverter_linux64.tar.gz
      - name: build config
        run: |
          echo "token = ${{ secrets.DEPLOY_TOKEN }}" >> subconverter/gistconf.ini
          cat > subconverter/generate.ini <<EOF
          [surge-sub]
          target=surge
          url=${{ secrets.SUBURL }}
          filename=surge-sub
          ver=4
          udp=true
          exclude=拥挤|海外|测速|官网
          emoji=true
          tfo=true
          path=surge-sub.list
          list=true
          EOF
          ./subconverter/subconverter -g

      - name: Deploy
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.DEPLOY_TOKEN }}
          gist_id: ${{ secrets.GIST_ID }}
          gist_description: "private"
          gist_file_name: ${{ secrets.GIST_FILE_NAME }}
          file_path: ./subconverter/surge-sub.list
      - name: Notification failure
        if: ${{ failure() }}
        run: |
          curl https://sctapi.ftqq.com/${{ secrets.SCKEY }}.send?text=订阅列表生成失败
