#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2019 jianyun8023 <https://zhaojianyun.com>
#

name: Sync-Pulsar-Flink-Repository

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 * * * *'
  # release:
  #   types: [published]
env:
  ORIGIN_REPO: streamnative/pulsar-flink
  ORIGIN_REPO_BRANCH: master
  TARGET_REPO: jianyun8023/pulsar-flink
  TARGET_REPO_BRANCH: master
  TARGET_REPO_BRANCH_FORCE: false
  TZ: Asia/Shanghai
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout target repository
        uses: actions/checkout@v2
        with:
          repository: ${{ env.TARGET_REPO }}
          ref: ${{ env.TARGET_REPO_BRANCH }}
          persist-credentials: false
      - name: rebase upstream repository
        run: |
          ls -a
          git remote add upstream https://github.com/$ORIGIN_REPO
          git fetch upstream
          git rebase upstream/$ORIGIN_REPO_BRANCH
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          repository: ${{ env.TARGET_REPO }}
          branch: ${{ env.TARGET_REPO_BRANCH }}
          force: ${{ env.TARGET_REPO_BRANCH_FORCE }}
          github_token: ${{ secrets.DEPLOY_TOKEN }}